version: '3.7'

services:

  sailstranslate:
    image: idocoh/sails-translate:latest
    container_name: sailstranslate
    restart: always
    ports:
      - '80:1337'
    depends_on:
      - nodered
    links:
      - nodered
    environment:
       MONGO_URI: mongodb://maor:123456@mongoido:27017/maor


  nodered:
    image: idocoh/nodered-translate:latest
    container_name: nodered
    restart: always
#    ports:
#      - '1880:1880'
    depends_on:
      - mongoido
    links:
      - mongoido
    environment:
       MONGO_URI: mongodb://maor:123456@mongoido:27017/maor

  mongoido:
    image: bitnami/mongodb
    container_name: mongoido
    restart: always
    ports:
      - '27017:27017'
    environment:
       MONGODB_USERNAME: maor
       MONGODB_PASSWORD: 123456
       MONGODB_DATABASE: maor
